### ISSUE TITLE
Source for libraries

### ISSUE THREAD

**Issue by Furao** [analogdevicesinc/no-OS#10]
Is there anyway to get the source for the prebuilt libraries in this repository? You can respond to my email linked to this account if you would rather.

Thanks,
Robbie VanVossen
DornerWorks

**Comment by amistad000** [comment]
Hi Robbie,  
Please refer [response to adc_capture function issue in ad9361 code](https://ez.analog.com/message/246145#246145) 

Good Luck 
Amistad
