### ISSUE TITLE
In xilinx_i2c.c: XIIC_REPEATED_START macro error?

### ISSUE THREAD

**Issue by jmichel3** [analogdevicesinc/no-OS#1046]
In xilinx_i2c.c, the macro `XIIC_REPEATED_START` is used regardless of whether the type of the IIC descriptor is `IIC_PL` or `IIC_PS`. For example, see the definition of `xil_i2c_write()` from lines 392-446:

https://github.com/analogdevicesinc/no-OS/blob/8985cad9d88d4b78ab967381c99aa76b297e938c/drivers/platform/xilinx/xilinx_i2c.c#L392-L446

The Xilinx driver iicps_v3_10, however, defines `XIICPS_REP_START_OPTION` instead of `XIIC_REPEATED_START`. For the case where the IIC descriptor type is `IIC_PS`, should the correct macro be `XIICPS_REP_START_OPTION`?

**Comment by buha** [comment]
Your reasoning is correct, here's the doc for XIicPs_SetOptions():
```
* @param	Options contains the specified options to be set. This is a bit
*		mask where a 1 means to turn the option on. One or more bit
*		values may be contained in the mask. See the bit definitions
*		named XIICPS_*_OPTION in xiicps.h.
```

**Comment by jmichel3** [comment]
Awesome, thank you!
