### ISSUE TITLE
projects with possible DDR corruption 

### ISSUE THREAD

**Issue by sarpadi** [analogdevicesinc/no-OS#1064]
Several no-os projects are using an explicit DDR memory region for storing samples. This will most likely lead to the program overwriting itself and therefore crashing since it is not known if that particular area of memory is free or not at runtime. Below are the projects which seem to implement the rx buffer this way:

https://github.com/analogdevicesinc/no-OS/blob/c50ead90443edd8812e2584ebe926f3ab60c48b5/projects/ad7616-sdz/src/ad7616_sdz.c#L131

https://github.com/analogdevicesinc/no-OS/blob/c50ead90443edd8812e2584ebe926f3ab60c48b5/projects/ad6676-ebz/src/parameters.h#L64

https://github.com/analogdevicesinc/no-OS/blob/c50ead90443edd8812e2584ebe926f3ab60c48b5/projects/ad7768-evb/src/parameters.h#L50

https://github.com/analogdevicesinc/no-OS/blob/c50ead90443edd8812e2584ebe926f3ab60c48b5/projects/ad713x_fmcz/src/ad713x_fmc.c#L236

https://github.com/analogdevicesinc/no-OS/blob/c50ead90443edd8812e2584ebe926f3ab60c48b5/projects/ad7768-1fmcz/src/ad77681evb.c#L159

https://github.com/analogdevicesinc/no-OS/blob/c50ead90443edd8812e2584ebe926f3ab60c48b5/projects/ad9083/src/parameters.h#L63

The solution should look something like this:

https://github.com/analogdevicesinc/no-OS/blob/c50ead90443edd8812e2584ebe926f3ab60c48b5/projects/adaq7980_sdz/src/adaq7980_sdz.c#L61

Another solution would be dividing the DDR memory using the linker script (setting a smaller size) and then using the remaining free memory for buffers

The list may be incomplete

**Comment by buha** [comment]
moved to EZ
https://ez.analog.com/microcontroller-no-os-drivers/f/discussions/569443/projects-with-possible-ddr-corruption
