### ISSUE TITLE
Bugs in axi_dmac_default_isr()

### ISSUE THREAD

**Issue by jmichel3** [analogdevicesinc/no-OS#1074]
https://github.com/analogdevicesinc/no-OS/blob/cbd8405892eeadc4383a6d8ddc3644fb9a6f4743/drivers/axi_core/axi_dmac/axi_dmac.c#L65

In its current implementation, I think the ISR will stop submitting transfers only when the first transfer finishes, asserts EOT, and clears `big_transfer.size.` In other words, as long as no transfers have finished yet, the ISR will continue submitting transfers of length 0 even after it has queued the entire `big_transfer` length. 

I think the second condition in this if statement should be something like `(dmac->big_transfer.size_done == dmac->big_transfer.size)`. This could ensure that the SOT branch stops executing after the appropriate number of transfers have been queued.

Also, another potential vulnerability is if `big_transfer.size `is very large, is it conceivable that an EOT could fire before the chain of SOT's have finished queuing all of the transfers? If so, the EOT logic would then write `big_transfer.size` to 0 and preempt the remaining transfers from being queued.

**Comment by danmois** [comment]
Hello,

The current master branch of the repository has this problem solved.

Regards,
George
