### ISSUE TITLE
I noticed some strange issues when initializing the AXI_dmac IP using code from no-OS

### ISSUE THREAD

**Issue by gitQqqHs** [analogdevicesinc/no-OS#1108]
I noticed some strange issues when initializing the AXI_dmac IP using code from no-OS.
I found in the axi_dmac source code that req_src_address only uses the [30:3] range, which moves the address value three bits to the right. However, the no-OS code does not shift the associated address, which can leadIP to incorrect address configuration if you are not careful. The point is that the documentation on the official website does not address this problem. It will take a lot of time to develop. Hopefully this will be explained in the relevant code.
I use the latest HDL library

**Comment by adrimbarean** [comment]
Hello and apologies for the late reply. We usually use [EngineerZone](https://ez.analog.com/)  even for bug reports so the issues here can get ignored for a while.

Do you happen to have links that showcase the issue?

Regards,
Andrei
