### ISSUE TITLE
AD738x driver SPI mode

### ISSUE THREAD

**Issue by denny61302** [analogdevicesinc/no-OS#1151]
Hi,

I try to port the ad738x driver to my project (STM32WB55). There are some unpredictable outcomes when I use the driver.

https://github.com/analogdevicesinc/no-OS/blob/06038bb87cd4cc754a3ff84f05481f09774e99a6/projects/ad738x_fmcz/src/ad738x_fmc.c#L84

I found the SPI mode setting is not the same one I saw on the Analog Device EngineerZone.
https://ez.analog.com/data_converters/precision_adcs/f/q-a/534703/ad7380-spi-settings

Should be SPI mode 1 or mode 3?
https://www.analog.com/en/analog-dialogue/articles/introduction-to-spi-interface.html#:~:text=SPI%20is%20a%20synchronous%2C%20full,popular%204%2Dwire%20SPI%20interface.

**Comment by mchindri** [comment]
Hi Denny,

Indeed it seems that SPI_MODE_3 is the way to go. We will do a test and apply the fix if needed.
Thanks.

Regards,
Mihail
