### ISSUE TITLE
Xilinx GPIO input routine fails for .number>=32

### ISSUE THREAD

**Issue by prwang** [analogdevicesinc/no-OS#1153]
https://github.com/analogdevicesinc/no-OS/blob/304003481c3ed2c0c6f45fe66622a35c7d59d315/drivers/platform/xilinx/xilinx_gpio.c#L223

This line permanently reduced desc->number by 32 and all following xil_gpio_get_value will read the wrong GPIO pin.

**Comment by mchindri** [comment]
fixed: https://github.com/analogdevicesinc/no-OS/pull/1154
