### ISSUE TITLE
const correctness

### ISSUE THREAD

**Issue by atsju** [analogdevicesinc/no-OS#1233]
I will only take one example of adxl372.h but I think your drivers are full of these issues.

```C
int32_t adxl372_spi_reg_read(struct adxl372_dev * dev,
                             uint8_t              reg_addr,
                             uint8_t *            reg_data);
```
when a function does not modify the content of a pointer it shall be a pointer to const like 

```C
int32_t adxl372_spi_reg_read(const struct adxl372_dev * dev,
                             uint8_t              reg_addr,
                             uint8_t *            reg_data);
```
This makes everything much easier for developper.

**Comment by adrimbarean** [comment]
Hello,

Thank you for bringing this topic up.

Could you be more specific about the end goal of this change?

There are a lot of examples where we intend to change the contents of the structure using the API, for example, the [set bandwidth API](https://github.com/analogdevicesinc/no-OS/blob/master/drivers/accel/adxl372/adxl372.c#L223).

Regards,
Andrei

**Comment by atsju** [comment]
Hello,

Only when you don't intent to change the content then it should be marked as const.
It is only a good coding practice (the developper knows the structure is untouched without looking inside the function).

Regards,
Julien

**Comment by buha** [comment]
Hi Julien,

I acknowledge, this is good coding practice but lacking it may be compensated by good documentation.
It would require a lot of in-code changes, probably too many to care for now. We could just try to document things better.
But of course, feel free to create a pull request with such changes.
