### ISSUE TITLE
Maybe  this addr should be updated to 'XPAR_AXI_AD9680_CORE_BASEADDR' and 'XPAR_AXI_AD9144_CORE_BASEADDR'?

### ISSUE THREAD

**Issue by Marylover** [analogdevicesinc/no-OS#1239]
https://github.com/analogdevicesinc/no-OS/blob/08f452b0036c70cc2ed2865c67ba8a91d5eee6b3/projects/fmcdaq2/src/app/parameters.h#L79

**Comment by adrimbarean** [comment]
Hello,

Thank you for the interest in the code base!

These defines are automatically generated by the Vivado/Vitis toolchain when interpreting the HDL design. The name is derived from the name given to the IP core [here](https://github.com/analogdevicesinc/hdl/blob/master/projects/daq2/common/daq2_bd.tcl#L89) and the type of core it is, plus some useful suffixes and prefixes.

If we wanted to change it, the change must first happen in the repository linked above.

Regards,
Andrei
