### ISSUE TITLE
Altera Build Problems

### ISSUE THREAD

**Issue by desanchezrosales** [analogdevicesinc/no-OS#1247]
Hello,

I am having lots of issues building the NO-OS project for an altera board (DE-10 Standard). We are using the ARRADIO daughter card, which contains the AD9361 chip.  I am using windows 10.

I have tried to make the makefile in the No-Os/projects/ad9361 folder and have added the PLATFORM = altera to the header. But this fails to compile with error:

../../tools/scripts/generic.mk:171: *** 'No HARDWARE for altera found. Add .sopcinfo file'.  Stop.

Moreover, I have also tried to compile just the make file in No-Os/projects/ad9361/src  named Makefile.generic and changing the PLATFORM=altera. But this also fail for many reasons:

1) files are in different directories for instance, the file ad9361.h includes no-os/gpio.h but it needs to be just gpio.h

2) There are missing files, like altera_avalon_regs.h that is completely missing from the project. I was able to find this file in the files belonging to my quartus but I don't know if that's the correct file.

3)There are missing files like io.h that I was able to find in the quartus files as well but there are different files with the same name so i don't know which one to use.

I feel that I am missing something key here. 

Ideally, I would like to use the api and the main.c files (along with the hdl) to operate my SDR without having to boot into anything. Is this even possible?

Thank you in advance!

**Comment by adrimbarean** [comment]
Hello,

You would need to "Add .sopcinfo file". This file is a hardware description file generated by building the HDL. more details on that [here](https://wiki.analog.com/resources/fpga/docs/build). When you have built this file you need to copy it to the project folder before calling make. If the appropriate toolchain is installed the project should be created.

On a tangential note: the issues tab here is not too used or monitored. We should try using the [EngineerZone Forum](https://ez.analog.com/) to post the majority of questions and answers. It features a large and vibrant community and a lot of questions and answers from before, which make finding answers much easier. :)

Kind regards,
Andrei
