### ISSUE TITLE
xparameters.h

### ISSUE THREAD

**Issue by zhangdaojun** [analogdevicesinc/no-OS#13]
When I build the AD7768-EVB.c project,I have add AD7768-EVB Main Driver,Xilinx Platform Drivers,AD7768 Driver,ADC Core Driver,But can't pass,it prompt lack of xparameters.h.Can you help me to solve the problem?thanks!

**Comment by a0020924** [comment]
I meet the same problem

**Comment by dbogdan** [comment]
"xparameters.h" is generated when the BSP project is created. Some instructions can be found on the wiki: https://wiki.analog.com/resources/fpga/xilinx/software_setup
