### ISSUE TITLE
How can I turn off the AGC function of the two receiving channels of ad9361?

### ISSUE THREAD

**Issue by NTUGY** [analogdevicesinc/no-OS#1420]
Hi,
How can I turn off the AGC function of the two receiving channels of ad9361?
Best Regards!

**Comment by buha** [comment]
Hi @NTUGY ,
This is how you control the gain control:
https://github.com/analogdevicesinc/no-OS/blob/master/projects/ad9361/src/main.c#L227-L228

And here are the possible values:
https://github.com/analogdevicesinc/no-OS/blob/master/drivers/rf-transceiver/ad9361/ad9361.h#L2907-L2912
