### ISSUE TITLE
Problem to build a project

### ISSUE THREAD

**Issue by fabien637** [analogdevicesinc/no-OS#1436]
I try to build the no-OS ad9361 project on Windows but when I run the make command, an error appears telling me that 'xsct' is "not recognized as an internal or external command , an executable program or a command file."

Can you help me ?

![Capture d’écran 2022-07-12 121454](https://user-images.githubusercontent.com/52382710/178467716-fbb28cf4-eab0-4eb2-8228-94df1b58abce.png)

**Comment by danmois** [comment]
Hello fabien,

Did you run the following command: C:\Xilinx\Vitis\2021.1\settings64.bat ?

After running it your build should be fine.

Regards,
George

**Comment by danmois** [comment]
Please open a thread at https://ez.analog.com/microcontroller-no-os-drivers/ if the problem is not solved.

Regards,
George
