### ISSUE TITLE
Problem about NO-OS Project Build

### ISSUE THREAD

**Issue by wang5227004** [analogdevicesinc/no-OS#1447]
When I bulided the project of ad463x_fmcz( from https://github.com/analogdevicesinc/no-OS/tree/master/projects/ad463x_fmcz ), there was an error "You do not have sufficient permissions to perform this operation" .  I'm an administrator account. Can you give me some advice?

![image](https://user-images.githubusercontent.com/108658031/181171733-5af63f88-537e-437c-85a7-b3c7144aa98b.png)
![image](https://user-images.githubusercontent.com/108658031/181171820-d2383915-2c0b-4fee-bbeb-d37413748c49.png)

**Comment by danmois** [comment]
Hello,

You have to run cmd as administrator.

Regards,
George

**Comment by wang5227004** [comment]
It was the  result that  I runned  cmd as administrator. Except this, any others?

**Comment by danmois** [comment]
I have just build successfully the project, in a cmd window run as administrator. It is not sufficient that your Win account is Administrator, you also have to chose "Run as administrator" when opening a cmd window.

**Comment by wang5227004** [comment]
You are right. 
Thank you very much!
![image](https://user-images.githubusercontent.com/108658031/181197515-11877980-5ff5-4f48-95fe-6d8856ef8189.png)
