### ISSUE TITLE
AD9371 - bad initialization of structures 'xxx_adxcvr_init' in file headless.c

### ISSUE THREAD

**Issue by BreizhGeek** [analogdevicesinc/no-OS#1496]
Hi,

Since field 'cpll_enable' was removed from structure 'adxcvr_init' in commit 9b0152ca8bcc0fec96b3c91daf32b8c693fc9f0d (29 jul 2022), structure initialization is not done correctly in file no-OS/projects/ad9371/src/app/headless.c, line 229:

       struct adxcvr_init rx_adxcvr_init = {
		"rx_adxcvr",
		RX_XCVR_BASEADDR,
		0,
		3,
		1, <------------- to be removed
		1, 
		rx_lane_rate_khz,
		mykDevice.clocks->deviceClock_kHz,
	};
	struct adxcvr_init tx_adxcvr_init = {
		"tx_adxcvr",
		TX_XCVR_BASEADDR,
		3,
		3,
		0,  <------------- to be removed
		0,
		tx_lane_rate_khz,
		mykDevice.clocks->deviceClock_kHz,
	};
	struct adxcvr_init rx_os_adxcvr_init = {
		"rx_os_adxcvr",
		RX_OS_XCVR_BASEADDR,
		0,
		3,
		1,  <------------- to be removed
		1,
		rx_os_lane_rate_khz,
		mykDevice.clocks->deviceClock_kHz,
	};

**Comment by danmois** [comment]
Hi @BreizhGeek ,

Thank you for your notification! We will fix the problem.
