### ISSUE TITLE
no_os_udelay() implementation for Cortex-R5

### ISSUE THREAD

**Issue by BreizhGeek** [analogdevicesinc/no-OS#1538]
Hi,

For Cortex-R5 processors, It is maybe better to use Cortex-R5 specific function for usleep() in function no_os_udelay(). 

File no-OS/drivers/platform/xilinx/delay.c:

> 
void no_os_udelay(uint32_t usecs)
{
#ifdef _XPARAMETERS_PS_H_
#ifdef ARMR5
	usleep_R5(usecs);
#else
	usleep(usecs);
#endif
#else
	usleep_MB(usecs);
#endif
}

Same thing for function no_os_mdelay().

**Comment by buha** [comment]
Hi @BreizhGeek ,
That is true, but we don't really have R5 as supported platform and never quite tested running no-OS on it but it would make sense to have no-OS running on it.
Feel free to create a pull request, your suggestion is good.

**Comment by BreizhGeek** [comment]
Hi @buha ,
Thanks. For information, we  got code from your master branch and compiled it for Cortex-R5, with just a slight modification in one header file.  The executable runs as expected on Enclustra XU1/ST1 platform with AD9371 daughter board.
Congratulation! You did good job considering that is not a supported platform! 
Maybe we should collaborate on your cortex-R5 branch?
