### ISSUE TITLE
adxcvr_init structure initialization issue

### ISSUE THREAD

**Issue by mumubuntu** [analogdevicesinc/no-OS#1546]
Hello all

I'm trying to play with the zcu106 and the fmcomms8 (adrv9009) boards by using no-os from master branch.

The adxcvr_init structure defined within the axi_adxcvr.h file has 7 parameters.

This structure is initialized within the app_transceiver.c with 8 parameters.

It seems that the boolean parameter cpll_enable has been removed.

By removing this parameter within the app_transceiver.c, everything works fine !!!

Hope this helps you save time when playing with no-os software.

Best Regards.

MuMuBunTu

**Comment by danmois** [comment]
Hi @mumubuntu ,

Thank you for pointing out the problem. We will provide a solution asap.

Regards,
George
