### ISSUE TITLE
can't find Makefile.microblaze

### ISSUE THREAD

**Issue by abubakr88** [analogdevicesinc/no-OS#159]
Accordding to Build for Microblaze "https://github.com/analogdevicesinc/no-OS/blob/master/ad9361/sw" can't find Makefile.microblaze, what is the solution?

**Comment by iggy14750** [comment]
+1 although I am looking for the Zynq Makefile for this part. Does the `platform_xilinx` code work for Zynq? Could I just add the right Makefile around it? Be happy to send a PR. Thanks!

**Comment by buha** [comment]
You may see how `projects/adv7511` builds for `kc705` to understand how you could do a no-OS microblaze build.
I also found `scripts/microblaze.mk` which predates this github issue.
Closing this due to being old, feel free to reopen if you still have questions.
