### ISSUE TITLE
ad9361_validate_trx_clock_chain (ad9361.c) CMOS options not handled correctly

### ISSUE THREAD

**Issue by cfischb** [analogdevicesinc/no-OS#16]
When the port is set to CMOS, this validation function doesn't take the DDR and Dualport options into account. I. e. if the  Port is configured in CMOS mode with dualport and DDR option and the maximum samplerate of 61.44 MS/s is requested, the function calculates the data_clk variable to the  wrong value of 122.88e6 causing an error.

**Comment by buha** [comment]
This was likely fixed when ad9361 was moved to `projects/`. @cfischb please reopen if my assumption is not true.
