### ISSUE TITLE
Latest AD9371/9375 project

### ISSUE THREAD

**Issue by kikd** [analogdevicesinc/no-OS#160]
Hi.

I'm tried to make AD9371/9375 baremetal project for ZC706 board according to [AD9371/AD9375 No-OS Setup](https://wiki.analog.com/resources/eval/user-guides/mykonos/no-os-setup).
However, this repository contains 2 project([no-OS/ad9371](https://github.com/analogdevicesinc/no-OS/tree/master/ad9371) and [no-OS/projects/ad9371/src](https://github.com/analogdevicesinc/no-OS/tree/master/projects/ad9371/src)).

Which project is latest, and which is should I use?

Regards.

**Comment by mhennerich** [comment]
@dbogdan can comment more. But the one under projects is going the be the one moving forward, the other is going to be removed soon.

**Comment by kikd** [comment]
I understood.
Then obsolete one is removed, is wiki article will updated?

**Comment by dbogdan** [comment]
We still have to add an example of configuring the TX DMA in the new project - once this will be available, the old one will be completely removed and the wiki will be updated.

**Comment by kikd** [comment]
I got it.
Thanks for your answer.
