### ISSUE TITLE
ad9361_get_rx_rf_bandwidth() does not give the actual RX BW

### ISSUE THREAD

**Issue by cfischb** [analogdevicesinc/no-OS#17]
ad9361_get_rx_rf_bandwidth returns the input parameter of ad9361_set_rx_rf_bandwidth rather than the actual RF BW wich can differ quite a lot.

**Comment by buha** [comment]
UG-570, Rev. A, page 9, there is indeed a table showing desired BBBW and actual BBBW. This function does what it says. I might make sense to create a `ad9361_get_rx_rf_actual_bandwidth()` in which case one should create a new issue labeled with feature request for that.
