### ISSUE TITLE
AD9361 settings

### ISSUE THREAD

**Issue by KhyatiJadhav** [analogdevicesinc/no-OS#1736]
We are using NO-OS open source code to configure AD9361 RF agile Transceiver. The signal input to AD9361 is BPSK modulated signal at 70MHz with -40dBm power level. We tested this with 4800bps data rate and its working.
However, its not working and high data error is observed when we set the signal data rate to lower values like 2400 bps, 1200 bps and 300 bps.
Kindly suggest modifications in NO-OS code.

**Comment by buha** [comment]
Hi @KhyatiJadhav ,
I have created an EgineerZone thread on your behalf, please follow the discussion there.
https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/569427/ad9361-settings-2400-bps-1200-bps-and-300-bps
