### ISSUE TITLE
Relative include path in generic.mk causing build issues.

### ISSUE THREAD

**Issue by kister-jimenez** [analogdevicesinc/no-OS#2012]
I typically use no-OS as a submodule for quick projects to test something quickly. In my use-case, project folder or sources are outside the no-OS directory. So, I encountered issues with relative include paths in the generic.mk.

[generic.mk Line 240](https://github.com/analogdevicesinc/no-OS/blob/27d6d00229f18dfa55deb0870dc0144db6b1072a/tools/scripts/generic.mk#L240C9-L240C12)

[generic.mk Line 242](https://github.com/analogdevicesinc/no-OS/blob/27d6d00229f18dfa55deb0870dc0144db6b1072a/tools/scripts/generic.mk#L242)

We can replace "../../" with "$(NO-OS)/"

**Comment by rbolboac** [comment]
Helo @kister-jimenez ,

Thank you for reporting this.
We have merged the changes you suggested.

Best Regards,
Ramona
