### ISSUE TITLE
MAX32670 UART TX not checking transmit status before transmitting.

### ISSUE THREAD

**Issue by kister-jimenez** [analogdevicesinc/no-OS#2055]
https://github.com/analogdevicesinc/no-OS/blob/3f8ad251a837b28987f53d853344b232cd293043/drivers/platform/maxim/max32670/maxim_uart.c#L109C1-L123C2

This causes issues when transmitting more than MXC_UART_FIFO_DEPTH bytes. Other MAXIM UART platform drivers have this checking already.

**Comment by rbolboac** [comment]
Hello @kister-jimenez ,

Thank you for reporting this issue.
A fix has been integrated into main.
Let us know if this works for you.

Ramona

**Comment by kister-jimenez** [comment]
Thanks. This should work.
