### ISSUE TITLE
Any chance to support Zephyr OS?

### ISSUE THREAD

**Issue by denny61302** [analogdevicesinc/no-OS#2133]

**Comment by CiprianRegus** [comment]
Hi @denny61302,

I don't this will ever happen in the form that FreeRTOS is integrated in no-OS (which really just builds the FreeRTOS sources alongside no-OS). If you need a driver which is only available in no-OS (and not Zephyr), I suggest getting the source and header files from this repository and porting the platform specific calls to Zephyr instead.
