### ISSUE TITLE
Symbolic links break Windows MSDK builds 

### ISSUE THREAD

**Issue by Brandon-Hurst** [analogdevicesinc/no-OS#2135]
The symbolic links for the maxim_dma .c/.h files break builds out-of-the-box on Windows. Windows does not easily import symlinks from Git.

![image](https://github.com/analogdevicesinc/no-OS/assets/82959533/8a63e701-7bf2-448d-95dc-488293172280)

![image](https://github.com/analogdevicesinc/no-OS/assets/82959533/ee02a8eb-6c45-487f-b1e3-f7c2d8262720)

Suggested fix: Compile common HAL files via the Makefile includes rather than creating symbolic links.

**Comment by dbogdan** [comment]
This should fix the issue: https://github.com/analogdevicesinc/no-OS/commit/b2775b22b47ac1109adf166863bb0a033ef8de92

**Comment by Brandon-Hurst** [comment]
Hi Dragos,

Thanks, that's great! I noticed that the commit does not make the changes for MAX78000. This MCU should have the same changes done as well.
