### ISSUE TITLE
Symbolic links break Windows builds for MAX78000

### ISSUE THREAD

**Issue by Brandon-Hurst** [analogdevicesinc/no-OS#2143]
Same issue as #2135, but the fix was not applied for MAX78000.

**Comment by CiprianRegus** [comment]
Thanks for reporting this, https://github.com/analogdevicesinc/no-OS/commit/a599c6fe4cb6513d5a3fa0ff3003bb8de1b36dbc should fix the issue.

**Comment by Brandon-Hurst** [comment]
Yep, thanks!
