### ISSUE TITLE
ad9361_fastlock_prepare issue

### ISSUE THREAD

**Issue by slash-spb** [analogdevicesinc/no-OS#2211]
Do you mean FORCE_VCO_TUNE_ENABLE, instead FORCE_VCO_TUNE? 

https://github.com/analogdevicesinc/no-OS/blob/07649246bd8b7d15a7e21a7a4b0fcc602ec9c636/drivers/rf-transceiver/ad9361/ad9361.c#L5157 
https://github.com/analogdevicesinc/no-OS/blob/07649246bd8b7d15a7e21a7a4b0fcc602ec9c636/drivers/rf-transceiver/ad9361/ad9361.c#L5159

**Comment by buha** [comment]
thanks for the feedback, by looking at the user manual i agree it should be FORCE_VCO_TUNE_ENABLE and opened a pull request with the change
