### ISSUE TITLE
ADMV8818 SPI wrong addressing?

### ISSUE THREAD

**Issue by kylex2** [analogdevicesinc/no-OS#2293]
Hi,
Is the ADMV8818 code working? I haven't personally tried it yet but there is a discrepancy between the implementation and the specification in the datasheet. The datasheet specifies addressing using two bytes but the code is only using one byte. Can you please clarify this?

https://github.com/analogdevicesinc/no-OS/blob/656279589eeefb00ff785c7953fc60dad5052dd5/drivers/filter/admv8818/admv8818.c#L78-L88

vs
![Screenshot from 2024-09-14 16-00-02](https://github.com/user-attachments/assets/76e94e36-2cdc-4025-a3e1-296aa278bd09)
page 15
and
![Screenshot from 2024-09-14 16-00-27](https://github.com/user-attachments/assets/614f2a68-c999-40df-8ad1-04f8ba18e8e8)
page 6
from https://www.analog.com/media/en/technical-documentation/data-sheets/admv8818-ep.pdf

Thanks

**Comment by amiclaus** [comment]
Hello,

Thanks for pointing that out. Should be fixed with #2295 

Regards.
