### ISSUE TITLE
When I tried to use the bare metal driver ADRV9002, the following error occurred

### ISSUE THREAD

**Issue by NTUGY** [analogdevicesinc/no-OS#2371]
adrv9002_setup, 939: failed with "Failed to reset device and set SPI Config" (3)

**Comment by tfcollins** [comment]
Please post your question here: https://ez.analog.com/microcontroller-no-os-drivers/
Also provide the full log and versions (git hashes) of all repos and tools used. As well as hardware and configuration of HDL+ADRV9002. There is not enough info in your current post to provide any guidance.
