### ISSUE TITLE
ADIN1110 software power-down

### ISSUE THREAD

**Issue by damerste** [analogdevicesinc/no-OS#2394]
The function `adin1110_setup_phy` does not get the ADIN1110 MAC-PHY out of software power-down, or at least bit `PMA_SFT_PD` in register `PMA_PMD_CNTRL1` won't clear. If I replace the clearing of bit `PMA_SFT_PD` in register `PMA_PMD_CNTRL1` with clearing bit `CRSM_SFT_PD` in register `CRSM_SFT_PD_CNTRL` it works. As I don't know if this affects the behavior for the ADIN2111, I refrain from issuing a pull request.

**Comment by CiprianRegus** [comment]
Hi @damerste,

Thanks for reporting this. It seems the `PMA_SFT_PD` bit is a read only copy of `CRSM_SFT_PD` even though it's marked R/W in the datasheet. I've opened a PR (with the fix you suggested, which solves the issue) https://github.com/analogdevicesinc/no-OS/pull/2399. Should work for both the ADIN1110 and ADIN2111.
