### ISSUE TITLE
adv7511_zedboard_lib issue

### ISSUE THREAD

**Issue by tzhbingdu** [analogdevicesinc/no-OS#24]
I have a problem when building adv7511 project with Vivado2016.2 .

1.  Problem: axi_spdif_tx_core doesn't have a reg space. When exporting the hardware and launch SDK, it says can't find axi_spdif_tx_core address.
    Solution:  I re-package the axi_spdif_tx_core IP and create a reg space 0x43C0_0000 64K range. Is that right?

2. Problem: After solving axi_spdif_tx_core problem, SDK can't build the library with libHDMI_ZedBoardLib.a. It seems that tx_isr.o, tx_lib.o, 7511_hal.o and so on can't be generated. 

Do you have any suggestions?
Thanks.

**Comment by buha** [comment]
adv7511 was moved to `projects/` folder at some point and we ensure that the projects build with latest SDK's like 2018.3 or 2019.1.
9781c2b995e23487682778985f47cdd30fccda2b
