### ISSUE TITLE
no address in hdl-master mapped to AXI_AD9371_CORE_BASEADDR

### ISSUE THREAD

**Issue by amistad000** [analogdevicesinc/no-OS#256]
hi all 
in ad9371 noOS driver 
https://github.com/analogdevicesinc/no-OS/blob/1e00cdb1f2a5a925437e91f95004758be0007e26/ad9371/sw/headless.c#L63-L69
and 
https://github.com/analogdevicesinc/no-OS/blob/1e00cdb1f2a5a925437e91f95004758be0007e26/ad9371/sw/headless.c#L115-L123
and 
https://github.com/analogdevicesinc/no-OS/blob/1e00cdb1f2a5a925437e91f95004758be0007e26/ad9371/sw/platform_xilinx/parameters.h#L43

using the define macro of "AXI_AD9371_CORE_BASEADDR" which is no longer existing in 
https://github.com/analogdevicesinc/hdl/tree/master/projects/adrv9371x

they're replaced by 
"XPAR_RX_AXI_AD9371_TPL_CORE_TPL_CORE_BASEADDR"
"XPAR_TX_AXI_AD9371_TPL_CORE_TPL_CORE_BASEADDR"
"XPAR_RX_OS_AXI_AD9371_TPL_CORE_TPL_CORE_BASEADDR"

we don't know what and how to mapped the address in noOS sw driver. 

plz show me the clue. 
thanks 

amistad

**Comment by dbogdan** [comment]
Hi,
Can you please use these sources instead: https://github.com/analogdevicesinc/no-OS/blob/master/projects/ad9371 ?
The TPL addresses are defined in this version (https://github.com/analogdevicesinc/no-OS/blob/master/projects/ad9371/src/devices/adi_hal/parameters.h#L137).
Thanks,
Dragos
