### ISSUE TITLE
dmac_core.h, config.h file errors for the adv7511 branch of 2018_r2

### ISSUE THREAD

**Issue by badegoke-f1** [analogdevicesinc/no-OS#258]
I have followed the instructions to the letter at [https://wiki.analog.com/resources/fpga/xilinx/kc705/adv7511](url)

I am using a Xilinx Zc706 development board for hdmi tx. I have downloaded the respective release versions hdl-2018_r2 and no-OS-2018_R2 for my version of  Vivado 2018.2 and SDK 2018.2.

After building the SDK project, I get errors "cannot find dmac_core.h" called in "cf_hdmi.c". I then looked the the no-OS folders and found the missing file. So I has to include "dmac_core" and "platform_drivers" to the project include paths along with "inc" and "lib" paths as stated in the above link to fix the error. 

However, this throws another error "cannot find config.h" which is called in "platform_drivers.h".

I have spend 2 futile days on this and any help or suggestion will be highly appreciated.

Thanks 
Bade

**Comment by adrimbarean** [comment]
I think that this issue was addressed in [this](https://ez.analog.com/fpga/f/q-a/116845/dmac_core-h-config-h-file-errors-for-the-adv7511-branch-of-2018_r2) question from EngineerZone.

The project is still in progress at this time, but it can be used as described in the comment. Closing.
