### ISSUE TITLE
Improve GCD algorithm efficiency

### ISSUE THREAD

**Issue by gregoryng** [analogdevicesinc/no-OS#27]
The simple GCD algorithm in ADF4350.c:

https://github.com/analogdevicesinc/no-OS/blob/master/drivers/adf4350/adf4350.c#L147

trivially works (eventually), but could be quite a bit more efficient using this algorithm:
https://en.wikipedia.org/wiki/Euclidean_algorithm#Implementations

**Comment by dNechita** [comment]
Hi!

This is really helpful. Thanks for pointing it out!
I've added a pull request that implements what you have suggested: https://github.com/analogdevicesinc/no-OS/pull/28

Thanks!
