### ISSUE TITLE
 no-OS/drivers/ad717x/ad717x.c AD717X_WaitForReady

### ISSUE THREAD

**Issue by Silhouette2022** [analogdevicesinc/no-OS#31]
Driver file  no-OS/drivers/ad717x/ad717x.c  has a bug inside AD717X_WaitForReady function.
According to manual ready bit in status register set to 0 if conversion has been completed and set to 1 if data is awaiting. Metioned function test that bit for 1 and return success status. So, instead of testing for 1 it should test for 0 value.

**Comment by dbogdan** [comment]
Thanks for letting us know about this and sorry for the inconvenience.
The issue should be fixed now: https://github.com/analogdevicesinc/no-OS/commit/8251dfc96b85e1b1f3875dcd8a35633cea075e42
