### ISSUE TITLE
No single shown in SA when enable DAC_DMA_EXAMPLE

### ISSUE THREAD

**Issue by amistad000** [analogdevicesinc/no-OS#357]
Hi 
There is no single shown in SA when enable DAC_DMA_EXAMPLE in the following codes. 
https://github.com/analogdevicesinc/no-OS/blob/fb0b6271e1ead601f4be05ca8d34a4e8249bef97/projects/ad9371/src/app/headless.c#L879-L886

Please help to solve this issue. 
Sincerely 
H.A.

**Comment by amiclaus** [comment]
Hello,

Can you try please these profile: https://github.com/analogdevicesinc/no-OS/tree/master/projects/ad9371/profiles/tx_bw100_orx_bw100_rx_bw100

Thank you,
Antoniu

**Comment by amiclaus** [comment]
**Update**: should be fixed now with PR: #361 

Looking forward to your feedback.

Thank you,
Antoniu

**Comment by amistad000** [comment]
Hi Antoniu
confirmed.
the issue will be closed. 
H.A.
