### ISSUE TITLE
Initialisation of structures in driver usage in example is missing

### ISSUE THREAD

**Issue by prashantd2709** [analogdevicesinc/no-OS#42]
Example of driver usage in wiki missing the initialization of structures used. I am stuck at this point. So it will be of great help if someone provides the same.
Thanks

**Comment by dbogdan** [comment]
Hi,
What exact driver do you want to use?
Thanks,
Dragos

**Comment by prashantd2709** [comment]
I want to use AD7124 no-os drivers.
Thanks
