### ISSUE TITLE
Can't find base address definitions

### ISSUE THREAD

**Issue by jharm1** [analogdevicesinc/no-OS#44]
I'm trying to build the no-OS software for Xilinx Zed board connected to the AD9371.  The following base addresses are not found in SDK after the .c and .h files have been imported from this repository at the 'master' branch:

XPAR_AXI_AD9371_TX_DMA_BASEADDR
XPAR_AXI_AD9371_RX_DMA_BASEADDR
XPAR_AXI_AD9371_RX_CLKGEN_BASEADDR
XPAR_AXI_AD9371_TX_CLKGEN_BASEADDR
XPAR_AXI_AD9371_RX_OS_CLKGEN_BASEADDR
XPAR_AXI_AD9371_CORE_BASEADDR
XPAR_AXI_AD9371_RX_JESD_RX_AXI_BASEADDR
XPAR_AXI_AD9371_TX_JESD_TX_AXI_BASEADDR
XPAR_AXI_AD9371_RX_OS_JESD_RX_AXI_BASEADDR
XPAR_AXI_AD9371_RX_XCVR_BASEADDR
XPAR_AXI_AD9371_TX_XCVR_BASEADDR
XPAR_AXI_AD9371_RX_OS_XCVR_BASEADDR
XPAR_PS7_SPI_0_BASEADDR
XPAR_PS7_SPI_0_DEVICE_ID

Is there a file I'm missing with these definitions?  If not, what should the addresses be?

**Comment by VIVOkitty** [comment]
I come across the same question today. Have you solved it?

**Comment by dbogdan** [comment]
The ADRV9371/PCBZ requires an HPC connector, while on the ZedBoard there is only one LPC one. We don't have any AD9371 reference design for ZedBoard, so I guess that you are using the predefined ZedBoard hardware target - in this case the errors are expected.

**Comment by buha** [comment]
There is no design to support ad9371 on ZedBoard as @dbogdan said. Also see https://ez.analog.com/fpga/f/q-a/116629/ad9371-and-zed-board
Closing this issue.
