### ISSUE TITLE
Headers in ad7124.h

### ISSUE THREAD

**Issue by niliopoulos** [analogdevicesinc/no-OS#48]
Hello,
is it possible to move the following includes:
```c++
#include <stdint.h>
#include "platform_drivers.h" 
```
From ad7124.c to ad7124.h because gcc complains for integral types and the spi_desc?

Thanks!

**Comment by dbogdan** [comment]
Hi,

Sorry, we'll fix this.

Thanks,
Dragos

**Comment by mirceacaprioru** [comment]
Fixed with 35878e83bc45ee846971249c5065379c89d12d62 and ad22a7b32ff8aa5c49affbeb29fcf2fa73c92102
