### ISSUE TITLE
adxl372.h bit mask for ADXL372_FIFO_CTL_SAMPLES_MSK

### ISSUE THREAD

**Issue by wko27** [analogdevicesinc/no-OS#49]
Hello!

Should ADXL372_FIFO_CTL_SAMPLES_MSK should be BIT(0) instead of BIT(1) since bit 1 is part of the ADXL372_FIFO_CTL_MODE_MSK?

**Comment by stefpopa** [comment]
Hello,

Yes, you are right! Thank you very much for pointing this out! I will fix this. However, this mask wasn't used anywhere in the driver, so no other change is required. 

-Stefan
