### ISSUE TITLE
Ran static analysis tool - Klocwork Insight - on source, reported issues

### ISSUE THREAD

**Issue by dknowles67** [analogdevicesinc/no-OS#5]
I ran the static software analysis tool called Insight, by Klocwork on our source code, including the no-OS drivers we are using supplied from this repository.  The tool reported a few issues, as outlined below:

File ad9361.cpp:
function ad9361_get_split_table_gain:
rx_gain->tia_index is used to index
tia_table (array size = 2), but is not range checked to make sure tia_index is < 2

function ad9361_rssi_setup:
j -1 is used to index weight array (array size = 4) without range checking to make sure j is between 1 and 4 (such that j-1 will be between 0 and 3).

function ad9361_validate_trx_clock_chain:
loops from ADC_FREQ to RX_SAMPL_CLK, should loop to RX_SAMPL_FREQ.
rx_path_clks is an array indexed by ad9361_pdata_rx_freq type.  (enumeration)

function ad9361_parse_fir:
            ret = sscanf(line, "BWRX %"PRIu32, &phy->filt_rx_bw_Hz);
            ret = sscanf(line, "BWTX %"PRIu32, &phy->filt_tx_bw_Hz);
filt_rx_bw_Hz is unsigned, should be PRIu32, not PRId32
same with filt_tx_bw_Hz.

file ad9361.h
EXT_REF_CLK is one more that NUM_AD9361_CLKS, arrays are sized by NUM_AD9361_CLKS, but indexed with EXT_REF_CLOCK.

file ad9361_api.cpp
function ad9361_init:
memory not freed if zmalloc fails.

**Comment by mirceacaprioru** [comment]
Hi, 

Sorry for the delayed reply, since this we applied Codacy for our future development, so this will ensure we catch issues similar to the ones reported here. We are constantly trying to improve our code base, so thank you for helping us in this regard.

Thank you,
Mircea
