### ISSUE TITLE
getting a 0XFF value for all register..

### ISSUE THREAD

**Issue by tejasbhumkar** [analogdevicesinc/no-OS#53]
Good Morning!!!!

I'm using a processor AM5728 to interface(spi)  AD9364 trans-receiver. i wanted to read register value of ad9364 but i'm getting 0xff value for all the register...i supposed to get an default value for all the register.

Thank you!!

**Comment by dbogdan** [comment]
This is an issue with your custom implementation of the platform drivers. For this type of questions, please open threads on EZ (https://ez.analog.com/community/linux-device-drivers/microcontroller-no-os-drivers).
