### ISSUE TITLE
AD7771 : power mode not set properly

### ISSUE THREAD

**Issue by Steins7** [analogdevicesinc/no-OS#552]
The power mode isn't set in `ad7779_init()`. I believe it's just a copy-paste mistake, here is the current code (ad7779.c:1345) : 
```c
	dev->ref_type = init_param.ref_type;
	if (dev->ctrl_mode == AD7779_SPI_CTRL)
		ret |= ad7779_set_reference_type(dev, dev->ref_type);

	dev->pwr_mode = init_param.pwr_mode;
	if (dev->ctrl_mode == AD7779_SPI_CTRL)
		ret |= ad7779_set_reference_type(dev, dev->ref_type);
```
We can see that the function called is twice the same, and the parameter is also the same, hence the copy-paste mistake.

The correct code should be :

```c
	dev->ref_type = init_param.ref_type;
	if (dev->ctrl_mode == AD7779_SPI_CTRL)
		ret |= ad7779_set_reference_type(dev, dev->ref_type);

	dev->pwr_mode = init_param.pwr_mode;
	if (dev->ctrl_mode == AD7779_SPI_CTRL)
		ret |= ad7779_set_power_mode(dev, dev->pwr_mode);
```
It still wont work with that fix though because the enum used for the power configuration is also wrong, here is the current code (adc7779.h:196) :

```c
typedef enum {
	AD7779_HIGH_RES,
	AD7779_LOW_PWR,
} ad7779_pwr_mode;
```
But in the datasheet we see that it should be the opposite (see here : https://www.analog.com/media/en/technical-documentation/data-sheets/AD7779.pdf - p70) :

```c
typedef enum {
        AD7779_LOW_PWR,
	AD7779_HIGH_RES,
} ad7779_pwr_mode;
```
Thanks for your time

**Comment by amiclaus** [comment]
Hello, 

Thanks for spotting these issues. 
It should be solved with #561 

Regards,
Antoniu
