### ISSUE TITLE
adxl372.h is missing a close parenthesis

### ISSUE THREAD

**Issue by wko27** [analogdevicesinc/no-OS#58]
https://github.com/analogdevicesinc/no-OS/blob/master/drivers/adxl372/adxl372.h#L150

Cheers,
Andrew

**Comment by dbogdan** [comment]
Sorry for that. It was fixed: https://github.com/analogdevicesinc/no-OS/commit/6fad9db0aed4aeae5e1d75f5fb9afed2d608aa8d

Thanks,
Dragos
