### ISSUE TITLE
Multi Chip Sync - using wrong enumeration.

### ISSUE THREAD

**Issue by dknowles67** [analogdevicesinc/no-OS#6]
In file ad9361_api.cpp, function ad9361_do_mcs - the set state machine mode parameter is passing in the wrong parameter.  The latest version passes in ENSM_STATE_ALERT, when it should be passing in ENSM_MODE_ALERT.

**Comment by mirceacaprioru** [comment]
Fixed with 0ec093971a2b527538ba8d40cb286031681f6835
