### ISSUE TITLE
GPIO get direction returns wrong value when using PL gpio

### ISSUE THREAD

**Issue by zhaoxiaoguang** [analogdevicesinc/no-OS#608]
function int32_t gpio_get_direction(struct gpio_desc *desc, uint8_t *direction) in drivers/platform/xilinx/gpio.c returns wrong direction when using PL gpio. 

maybe should be like this: 
*direction = ((XGpio_GetDataDirection(extra->instance,channel) >> pin) & 0x01) ^ 0x1;

**Comment by buha** [comment]
Thanks @zhaoxiaoguang, thanks for reporting this.
I checked the xilinx documentation and seems you are right.
https://xilinx.github.io/embeddedsw.github.io/gpio/doc/html/api/group__gpio__v4__5.html#ga77090853c15dc3d72e2bfbc66e635ada

Your suggested change also looks correct. Will make sure this gets fixed soon.
