### ISSUE TITLE
Wrong return value of _gpio_init in gpio.c

### ISSUE THREAD

**Issue by l-digital** [analogdevicesinc/no-OS#659]
line 105 of no-OS/drivers/platform/xilinx/gpio.c

If error when init PL GPIO, the code jump to pl_error and free the previously allocated memory, and it is supposed the function should return a FAILURE. However, the "break" in line 105 will jump out of the   "switch" to line 134, which will return a SUCCESS. The coresponding PS GPIO part of the codes handle the same error scenario correctly without having "break".

**Comment by amiclaus** [comment]
Done with #669

Thank you!
