### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by l-digital** [analogdevicesinc/no-OS#660]
line 101 and line 103 are the same in no-OS/prjects/ad9361/src/ad9361.c (both are "phy->tx_dac_init = init_param->tx_dac_init;"), one of them should be removed.

**Comment by amiclaus** [comment]
Hello,

These are the lines 101-103 from the file you specified.

https://github.com/analogdevicesinc/no-OS/blob/b438e7c075dd662925bfbf27123313ba371542c2/projects/ad9361/src/ad9361.c#L101-L103

Please mention again the correct file where you found these issues.

**Comment by l-digital** [comment]
Sorry, I mentioned a wrong file name. The correct file name is "no-OS/prjects/ad9361/src/ad9361_api.c".

**Comment by amiclaus** [comment]
Done with #668 

Thank you!
