### ISSUE TITLE
code breakage: the newly updated create_project.tcl can not work under windows system

### ISSUE THREAD

**Issue by l-digital** [analogdevicesinc/no-OS#679]
Line 1 of file no-OS/tools/scripts/platform/xilinx/create_project.tcl
The newly updated version (commit b5472e6 on Jun 17, 2020) changes line 1  from "if { $argc != 3 } {" to " if { $argc != 6 } {" in order to accomodate the building of tinyiiod. However, the make file of no-OS/tools/scripts/windows.mk is not updated accordingly, which leads to build failure on line  471 (line 471 calls create_project.tcl).

**Comment by cristiantpop** [comment]
Hello,
Yes it breaks the makefile, please try this fix.
https://github.com/analogdevicesinc/no-OS/tree/win_mk_fix
