### ISSUE TITLE
Should not write two AXI_DAC_REG_DATA_SELECT registers in the loop

### ISSUE THREAD

**Issue by l-digital** [analogdevicesinc/no-OS#717]
Line 889-890 of file no-OS/drivers/axi_core/axi_dac_core/axi_dac_core.c

According to the DAC channel register map (https://wiki.analog.com/resources/fpga/docs/axi_ad9361) and the macro of AXI_DAC_REG_DATA_SELECT,  `axi_dac_write(dac, AXI_DAC_REG_DATA_SELECT(i), AXI_DAC_DATA_SEL_DDS);` or `axi_dac_set_datasel(dac, i, AXI_DAC_DATA_SEL_DDS);` should be more correct than these two lines' writing the two registers in the loop. Actually, some of those registers in these two lines do not exist in AD9361. Quite lot of confusions there. BTW, the parameter `chan` in function `axi_dac_set_datasel` has different meaning than the parameter `chan` in functions like `axi_dac_dds_set_frequency`,`axi_dac_dds_set_phase`,`axi_dac_dds_set_scale`, and I would suggest using different parameter name (for example channel) in function `axi_dac_set_datasel` for better code clarity.

**Comment by adrimbarean** [comment]
Hello,

For this as well the driver has been updated and I think the same problems are not present anymore.

Regards,
Andrei
