### ISSUE TITLE
AD7616 SOFTWARE MODE with STM32H743ZI2

### ISSUE THREAD

**Issue by dawn98f** [analogdevicesinc/no-OS#734]
Hello,

Good day, I am a intern trying to get the AD7616 to work with STM32h743ZI2. My main objective is to use the AD7616 in software mode and convert the analog input

and read them over SPI. 

The sequence of steps, I will be following are as follows: -

1. Power ON.

2. Full reset.

3. Select the the Operational mode.

4. Reset again (partial or full, I am confused)

5. SPI Initialize

6. Set channel register.

7. Start dummy conversion.

8. After the dummy conversion is done initiate the real conversion.

9. Read results from registers.

Is this correct or am I missing something.

I have gone through the wiki page of AD7616.

https://analog-staging.dw1.cosmocode.de/resources/eval/user-guides/ad7616-sdz

From there I found the Github repository for analog devices for NO-OS AD7616.

https://github.com/analogdevicesinc/no-OS/tree/2016_R1/ad7616-sdz

https://github.com/analogdevicesinc/no-OS/blob/6fad9db0aed4aeae5e1d75f5fb9afed2d608aa8d/ad7616-sdz/ad7616.c

I have added these files to project in stm32.

However when I try to compile this project, I am getting this error -   ..\..\..\STM32 H743\noos-AD7616-sdz\platform_drivers.h(45): error:  #5: cannot open source input file "xparameters.h": No such file or directory.

I would appreciate any kind of input from you.

Look forward to your response.

Thank You.

**Comment by buha** [comment]
Closing this, let's continue the discussion on EngineerZone
https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/534642/ad7616-software-mode-with-stm32h743zi2
