### ISSUE TITLE
TX RF bandwidth: wrong check

### ISSUE THREAD

**Issue by DeadMaX** [analogdevicesinc/no-OS#806]
Hello,

At the line :

https://github.com/analogdevicesinc/no-OS/blob/36bf37d6edb933ac2fb6b7ad8e6f1efefffd3b4a/drivers/rf-transceiver/talise/api/talise.c#L2177

The code check the TX RF bandwitdh with a minimum of 15Mhz. However, the "profile configuration wizard" sofware allow us to use a 10 Mhz tx bandwidth. What value is wrong ?

Regards

**Comment by tfcollins** [comment]
Can you please report this issue here: https://ez.analog.com/wide-band-rf-transceivers/tes-gui-software-support-adrv9009-adrv9008-1-adrv9008-2/

No-OS is simply a user of the Talise API. We try to avoid changing code within it.

-Travis
