### ISSUE TITLE
spi read enter endless loop

### ISSUE THREAD

**Issue by xiaoweihua** [analogdevicesinc/no-OS#81]
hello
    the project for FMC_DAQ2 kcu105, 
ad9680_spi_read(dev, AD9680_REG_CHIP_ID_LOW, &chip_id); entering endless loop
  debug and found that malloc() failed  in spi_init() !!!

**Comment by adrimbarean** [comment]
Hello!
Can you, please, specify what version of no-OS and HDL you are using? Also note that this problem may appear if there is insufficient HEAP size on the Microblaze processor. To solve that you would need to increase it to 0x100000 in the linker script. Please follow instructions on this page:

https://wiki.analog.com/resources/fpga/xilinx/software_setup
