### ISSUE TITLE
#define I2C_LPC_PS7 0x40

### ISSUE THREAD

**Issue by ivantaran** [analogdevicesinc/no-OS#9]
On  hardware ZC706 with fmcomms1 on LPC port problem I2c_Init.
In file i2c_ps7.h

Change lines:
/\* IIC FMC Port selection */
# define I2C_HPC_PS7 0x20
# define I2C_LPC_PS7 0x20

To:
/\* IIC FMC Port selection */
# define I2C_HPC_PS7 0x20
# define I2C_LPC_PS7 0x40

**Comment by mirceacaprioru** [comment]
Since this the code has changed and parts of i2c_ps7 are no longer present in our repository.
