### ISSUE TITLE
There is no console command for AD9361 in the new version ?

### ISSUE THREAD

**Issue by imlaohe** [analogdevicesinc/no-OS#912]
I build the HDL project and the no-os project for AD9361. When I download the elf to my zedboard, there was message out. But I can not use the command to control my board.  And I found that there is no console command code in the project.  I use the 2019_r1 HDL version.

**Comment by imlaohe** [comment]
I build the HDL project and the no-os project for AD9361. I found that there is no console command in the code. I use the 2019_r2 version.

**Comment by mchindri** [comment]
I see this discussion is already here:
https://ez.analog.com/microcontroller-no-os-drivers/f/q-a/539817/there-is-no-console-command-for-ad9361-in-the-new-version
The support will continue there, I'am closing this issue.

**Comment by imlaohe** [comment]
thanks!!!!
